### ISSUE TITLE
Blazor 8 App error

### ISSUE THREAD

**Issue by idikasova** [soenneker/soenneker.blazor.tomselect#850]
System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Soenneker.Blazor.Utils.JsVariable.Abstract.IJsVariableInterop Lifetime: Singleton ImplementationType: Soenneker.Blazor.Utils.JsVariable.JsVariableInterop': Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Soenneker.Blazor.Utils.JsVariable.Abstract.IJsVariableInterop'.) (Error while validating the service descriptor 'ServiceType: Soenneker.Blazor.Utils.ModuleImport.Abstract.IModuleImportUtil Lifetime: Singleton ImplementationType: Soenneker.Blazor.Utils.ModuleImport.ModuleImportUtil': Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Soenneker.Blazor.Utils.ModuleImport.Abstract.IModuleImportUtil'.) (Error while validating the service descriptor 'ServiceType: Soenneker.Blazor.Utils.ResourceLoader.Abstract.IResourceLoader Lifetime: Singleton ImplementationType: Soenneker.Blazor.Utils.ResourceLoader.ResourceLoader': Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Soenneker.Blazor.Utils.ResourceLoader.Abstract.IResourceLoader'.) (Error while validating the service descriptor 'ServiceType: Soenneker.Blazor.TomSelect.Abstract.ITomSelectInterop Lifetime: Scoped ImplementationType: Soenneker.Blazor.TomSelect.TomSelectInterop': Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Soenneker.Blazor.Utils.ResourceLoader.Abstract.IResourceLoader'.)'

**Comment by soenneker** [comment]
Thanks for the issue, can you give it a try after updating?

**Comment by idikasova** [comment]
System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](String identifier, CancellationToken cancellationToken, Object[] args)
   at Soenneker.Blazor.Utils.ModuleImport.ModuleImportUtil.<>c__DisplayClass2_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Soenneker.Blazor.Utils.ModuleImport.ModuleImportUtil.ImportAndWait(String name, CancellationToken cancellationToken)
   at Soenneker.Blazor.Utils.ModuleImport.ModuleImportUtil.ImportAndWaitUntilAvailable(String name, String variableName, Int32 delay, CancellationToken cancellationToken)
   at Soenneker.Blazor.TomSelect.TomSelectInterop.<.ctor>b__2_0(CancellationToken token, Object[] _)
   at Soenneker.Utils.AsyncSingleton.AsyncSingleton`1.GetInternal(CancellationToken cancellationToken, Object[] objects)
   at Soenneker.Utils.AsyncSingleton.AsyncSingleton`1.Get(CancellationToken cancellationToken, Object[] objects)
   at Soenneker.Blazor.TomSelect.TomSelectInterop.Initialize(CancellationToken cancellationToken)
   at Soenneker.Blazor.TomSelect.TomSelect`2.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(IComponent component, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderEndpointComponent(HttpContext httpContext, Type rootComponentType, ParameterView parameters, Boolean waitForQuiescence)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by soenneker** [comment]
Have you tried not prerendering this component
